auth:
  hashing_string: 6NHHeMlkPptJqafxsVowwYlcKhI_cuCqftzkBaydJaY
  htpasswd_path: users.htpasswd
  session_max_age: 43200
cookie:
  name: pecan_sandy
  secure: true
  httponly: true
  samesite: Lax
  domain: null
  allowed_hosts:
  - dev.home.arpa
  - labs.home.arpa
server:
  port: 55000
  host: 0.0.0.0
redir:
  external_name: auth
  default_destination: dashboard
page:
  title: SEC540 Range Access
  template_path: login_template.html.j2
