version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - conftest
  - docstrings
  - homelab
  - httponly
  - setex
  - Taskfile
  - unsign
  - wsgi
ignoreWords: []
import: []
